---
# tasks file for aws_ans
- name: Create an S3 bucket
  amazon.aws.s3_bucket:
        name: mysui97363bucket
        state: present
        region: ap-south-1
        aws_access_key: "{{ aws1 }}"
        aws_secret_key: "{{ aws2 }}"
        tags:
          Environment: Dev
  register: s3_result

- name: Print bucket creation result
  debug:
     var: s3_result
